### ISSUE TITLE
Sectionned list

### ISSUE THREAD

**Issue by vpratfr** [thefuntasty/infinity#19]
Hi,

Great library, congrats. I wonder if you already have experience on how to get sections to work with your adapter?

Something like https://gist.github.com/gabrielemariotti/4c189fb1124df4556058

I have items with a date, and I would like to section them by day. Something like:

- 2017/10/12
- Item 1
- Item 2
- 2017/10/11
- Item 3
- Item 4
- 2017/10/09
- Item 5

They already come sorted by DESC data from my API.

**Comment by skywall** [comment]
Hello, these two are basically two different types of adapters and its going to be quite hard to implement this in Infinity. I recommend you to transform (flatten) your data to simple list with multiple ViewTypes and bind ViewHolder's as usual.

**Comment by vpratfr** [comment]
Got it working rather nicely with https://github.com/edubarr/header-decor

There is just a slight naming issue as mentionned on https://github.com/edubarr/header-decor/issues/67#issuecomment-280040232
